# Generated by Django 5.1.3 on 2024-11-29 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('price', models.FloatField(verbose_name='Укажите цену')),
                ('release_date', models.DateField(verbose_name='Укажите дату выпуска')),
                ('image', models.ImageField(upload_to='device_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mobile_devices.category')),
                ('features', models.ManyToManyField(related_name='devices', to='Mobile_devices.feature')),
            ],
        ),
    ]
